# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://ebertapp.io/docs/config and see the configuration
# details.
---
styleguide: cerclecrm/cercle
engines:
  credo:
    enabled: true
  fixme:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: false
  remark-lint:
    enabled: false
exclude_paths:
- bin
- config
- priv/repo
- test
- web/static/css
- web/static/js/adminlte
- web/static/vendor